### ISSUE TITLE
[common] [paraflow-metaserver] MetaServer api

### ISSUE THREAD

**Issue by ray6080** [dbiir/paraflow#27]
List all public interfaces of MetaServer.

Sub task of #22 

API:
+ `List<String> listDatabases()`
+ `List<String> listTables(String database)`
+ `Database getDatabase(String database)`
+ `Table getTable(String database, String table)`
+ `Column getColumn(String database, String table, String column)`
+ `Status createDatabase(Database database)`
+ `Status createTable(Table table)`
+ `Status deleteDatabase(String database)`
+ `Status deleteTable(String database, String table)`
+ `Status renameDatabase(String oldName, String newName)`
+ `Status renameTable(String database, String oldName, String newName)`
+ `Status renameColumn(String database, String table, String oleName, String newName)`
+ `Status createFiber(String database, String table, long value)`
+ `List<Long> listFiberValues(String database, String table, long value)`
+ `Status addBlockIndex(String database, String table, long fiberV, String beginTime, String endTime, String path)`
+ `List<String> filterBlockPaths(String database, String table, String timeLow, String timeHigh)`
+ `List<String> filterBlockPaths(String database, String table, long fiberV, String timeLow, String timeHigh)`

Models:
1. **Database**
`String name;`
`String locationUri;`
`User user;`
2. **Table**
`Database database;`
`long creationTime;`
`long lastAccessTime;`
`User owner;`
`String tableName;`
`String tableLocationUri;`
`List<Column> columns;`
3. **User**
`String userName;`
`String userPass;`
`String roleName;`
`long creationTime;`
`long lastVisitTime;`
4. **Column**
`Table table;`
`String colName;`
`String dataType;`
`int colIndex;`
5. **Status** (`Enum` type)
+ `OK`
+ `DATABASE_ALREADY_EXISTS`
+ `DATABASE_NOT_FOUND`
+ `TABLE_ALREADY_EXISTS`
+ `TABLE_NOT_FOUND`
+ `COLUMN_ALREADY_EXISTS`
+ `COLUMN_NOT_FOUND`
+ `FIBER_ALREADY_EXISTS`
+ `BLOCK_INDEX_ERROR`

**Comment by LemonGrassSmell** [comment]
grpc have completed 
meta.proto
MetaClient.java
MetaServer.java
MetaService.java
TestMetaClient.java
